/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forzon3;

import static forzon3.empoyeedas.jLabel10;
import static forzon3.empoyeedas.jLabel12;
import static forzon3.empoyeedas.jLabel16;
import static forzon3.empoyeedas.jLabel18;
import static forzon3.empoyeedas.jLabel20;
import static forzon3.empoyeedas.jLabel31;
import static forzon3.empoyeedas.jLabel37;
import static forzon3.empoyeedas.jLabel39;
import static forzon3.empoyeedas.jLabel49;
import static forzon3.empoyeedas.jLabel8;
import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.imageio.ImageIO;
import static javax.swing.GroupLayout.Alignment.CENTER;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.border.MatteBorder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author chaitany
 */
 class LabelRender implements TableCellRenderer{

    @Override
    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
    return(Component)value;
    }
    
}
public class Record extends javax.swing.JPanel {
   
    public  ResultSet rs=null;
    public Connection  con=null;
    public PreparedStatement pst=null;
public void connection(){
     try{
             con=DriverManager.getConnection("jdbc:mysql://localhost:3306/froze","root","");
    
      }
          catch(Exception e){
    System.out.println(e);    
        }
      }
public void resize3(JLabel a,String d){
      ImageIcon myimage1=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource(d)));
        Image img3=myimage1.getImage();
        Image img4=img3.getScaledInstance( a.getWidth(),a.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon i11=new ImageIcon(img4);   
       a.setIcon(i11);
}
         public void resize(JLabel a,BufferedImage d){
      ImageIcon myimage1=new ImageIcon(d);
        Image img3=myimage1.getImage();
        Image img4=img3.getScaledInstance(180,180,Image.SCALE_SMOOTH);
        ImageIcon i11=new ImageIcon(img4);   
       a.setIcon(i11);
}
                  public void resize1(JLabel a,BufferedImage d){
      ImageIcon myimage1=new ImageIcon(d);
        Image img3=myimage1.getImage();
        Image img4=img3.getScaledInstance(a.getWidth(),a.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon i11=new ImageIcon(img4);   
       a.setIcon(i11);
}

  public void PanelB(){
      jPanel1.setBorder(null);
      jPanel2.setBorder(null);
      jPanel4.setBorder(null);
      jPanel5.setBorder(null);
  }
 public void swithPanel(JPanel panel,JPanel panel1){
          Color myWhite = new Color(0,204,0);   
      panel1.setBorder(new MatteBorder(0, 0, 10, 0, myWhite)); 
   
        jLayeredPane1.removeAll();
        jLayeredPane1.add(panel);
        jLayeredPane1.repaint();
        jLayeredPane1.revalidate();
    }
 public void jt_refresh(){
     connection();

             
 DefaultTableModel add=new DefaultTableModel();
 add=(DefaultTableModel)jTable1.getModel();
        for(int i=jTable1.getRowCount()-1;i>=0;i--){
       
  
 add.removeRow(i);
         }
     try{
      pst=con.prepareStatement("SELECT * FROM `employee`");
     rs=pst.executeQuery();
     while(rs.next()){

JLabel jlb=new JLabel();
BufferedImage im= ImageIO.read(rs.getBinaryStream("image"));
jlb.setIcon(new ImageIcon(im));
jlb.setHorizontalAlignment(JLabel.CENTER);
resize(jlb,im);

add=(DefaultTableModel)jTable1.getModel();
add.addRow(new Object[]{String.valueOf(rs.getInt("sr_no")),
    rs.getString("name"),jlb
});
jTable1.getColumn("Image").setCellRenderer(new LabelRender());

     }
}
      catch (Exception ex) {
      System.out.print(ex);
      }

 }
    /**
     * Creates new form Record
     */
    public Record() {
        initComponents();
   jLabel31.setVisible(false);
   jPanel9.setVisible(false);
jt_refresh();
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel30 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        employee = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        error1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        ShopVendors = new javax.swing.JPanel();
        Supplier = new javax.swing.JPanel();
        street_vendor = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jPanel9 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        error5 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        jLabel113 = new javax.swing.JLabel();
        jLabel114 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        jLabel116 = new javax.swing.JLabel();
        jLabel117 = new javax.swing.JLabel();
        jLabel118 = new javax.swing.JLabel();
        jLabel119 = new javax.swing.JLabel();
        jLabel120 = new javax.swing.JLabel();
        jLabel121 = new javax.swing.JLabel();
        jLabel122 = new javax.swing.JLabel();
        jLabel123 = new javax.swing.JLabel();
        jLabel124 = new javax.swing.JLabel();
        jLabel125 = new javax.swing.JLabel();
        jLabel126 = new javax.swing.JLabel();
        jLabel127 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(null);
        add(jLabel30);
        jLabel30.setBounds(510, 140, 1694, 840);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setOpaque(false);

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        employee.setBackground(new java.awt.Color(102, 102, 102));
        employee.setOpaque(false);
        employee.setLayout(null);

        jTable1.setBackground(new java.awt.Color(51, 51, 51));
        jTable1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 255, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "sr.No", "Name", "Image"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.setOpaque(false);
        jTable1.setRowHeight(160);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        employee.add(jScrollPane1);
        jScrollPane1.setBounds(10, 70, 500, 615);

        jTextField1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        employee.add(jTextField1);
        jTextField1.setBounds(10, 10, 1400, 50);

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setLayout(null);

        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 51), 5));
        jPanel8.add(jLabel7);
        jLabel7.setBounds(680, 0, 400, 400);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 51), 5));
        jPanel6.setEnabled(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        error1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        error1.setForeground(new java.awt.Color(0, 255, 51));
        error1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 51, 255)));
        jPanel6.add(error1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 595, 50));

        jLabel22.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 204, 0));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("EMPLOYEE INFORMATION");
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 13, 655, 50));

        jLabel8.setBackground(new java.awt.Color(0, 204, 51));
        jLabel8.setForeground(new java.awt.Color(51, 204, 0));
        jLabel8.setOpaque(true);
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 655, 5));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 51, 255));
        jLabel9.setText("NAME:");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 595, 50));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 51, 255));
        jLabel10.setText("USER ID:");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 595, 50));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 255, 51));
        jLabel11.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 51, 255)));
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 595, 50));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 51, 255));
        jLabel12.setText("ADHAR_CARD NO:");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 595, 50));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 51, 255));
        jLabel13.setText("ADDRESS:");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 595, 50));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 51, 255));
        jLabel14.setText("CONTACT:");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 595, 50));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 51, 255));
        jLabel15.setText("DATE OF BIRTH:");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 595, 50));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 51, 255));
        jLabel16.setText("GENDER:");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 700, 595, 50));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 51, 255));
        jLabel17.setText("POSITION:");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 800, 595, 50));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 51, 255));
        jLabel18.setText("JOINING DATE:");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 900, 595, 50));

        jLabel19.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 51, 255));
        jLabel19.setText("EDUCATION:");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1000, 595, 50));

        jLabel20.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 51, 255));
        jLabel20.setText("SALARY:");
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1100, 595, 50));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 51));
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 51, 255)));
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 595, 50));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 51));
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 51, 255)));
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 595, 50));

        jLabel21.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 255, 51));
        jLabel21.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 51, 255)));
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 595, 50));

        jLabel23.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 255, 51));
        jLabel23.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 51, 255)));
        jPanel6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 650, 595, 50));

        jLabel24.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 255, 51));
        jLabel24.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 51, 255)));
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 750, 595, 50));

        jLabel25.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 255, 51));
        jLabel25.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 51, 255)));
        jPanel6.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 850, 595, 50));

        jLabel26.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 255, 51));
        jLabel26.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 51, 255)));
        jPanel6.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 950, 595, 50));

        jLabel27.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 255, 51));
        jLabel27.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 51, 255)));
        jPanel6.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1050, 595, 50));

        jLabel28.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 255, 51));
        jLabel28.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 51, 255)));
        jPanel6.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1150, 595, 50));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 1247, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jScrollPane3.setViewportView(jPanel7);

        jPanel8.add(jScrollPane3);
        jScrollPane3.setBounds(0, 0, 680, 615);

        jButton4.setBackground(new java.awt.Color(255, 51, 51));
        jButton4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 204, 51));
        jButton4.setText("LEAVE");
        jButton4.setToolTipText("LEAVE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton4);
        jButton4.setBounds(780, 530, 200, 50);

        jButton2.setBackground(new java.awt.Color(0, 204, 51));
        jButton2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 51, 255));
        jButton2.setText("EDIT");
        jButton2.setToolTipText("EDIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton2);
        jButton2.setBounds(780, 430, 200, 50);

        employee.add(jPanel8);
        jPanel8.setBounds(560, 70, 1080, 615);

        jLabel29.setText("jLabel29");
        employee.add(jLabel29);
        jLabel29.setBounds(100, 20, 48, 16);

        jButton1.setBackground(new java.awt.Color(0, 255, 51));
        jButton1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        employee.add(jButton1);
        jButton1.setBounds(1420, 10, 260, 50);

        jButton3.setBackground(new java.awt.Color(0, 255, 51));
        jButton3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        employee.add(jButton3);
        jButton3.setBounds(10, 705, 500, 50);

        jLayeredPane1.add(employee, "card2");

        javax.swing.GroupLayout ShopVendorsLayout = new javax.swing.GroupLayout(ShopVendors);
        ShopVendors.setLayout(ShopVendorsLayout);
        ShopVendorsLayout.setHorizontalGroup(
            ShopVendorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1730, Short.MAX_VALUE)
        );
        ShopVendorsLayout.setVerticalGroup(
            ShopVendorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );

        jLayeredPane1.add(ShopVendors, "card4");

        javax.swing.GroupLayout SupplierLayout = new javax.swing.GroupLayout(Supplier);
        Supplier.setLayout(SupplierLayout);
        SupplierLayout.setHorizontalGroup(
            SupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1730, Short.MAX_VALUE)
        );
        SupplierLayout.setVerticalGroup(
            SupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );

        jLayeredPane1.add(Supplier, "card5");

        street_vendor.setBackground(new java.awt.Color(102, 102, 102));
        street_vendor.setOpaque(false);
        street_vendor.setLayout(null);

        jTable2.setBackground(new java.awt.Color(51, 51, 51));
        jTable2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTable2.setForeground(new java.awt.Color(0, 255, 51));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "sr.No", "Name", "Image"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable2.setOpaque(false);
        jTable2.setRowHeight(160);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
        }

        street_vendor.add(jScrollPane2);
        jScrollPane2.setBounds(10, 70, 500, 615);
        street_vendor.add(jTextField2);
        jTextField2.setBounds(10, 10, 1400, 50);

        jLabel56.setText("jLabel29");
        street_vendor.add(jLabel56);
        jLabel56.setBounds(100, 20, 48, 16);

        jButton6.setBackground(new java.awt.Color(0, 255, 51));
        jButton6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton6.setText("Search");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        street_vendor.add(jButton6);
        jButton6.setBounds(1420, 10, 260, 50);

        jLayeredPane2.setLayout(new java.awt.CardLayout());

        jPanel9.setBackground(new java.awt.Color(51, 51, 51));
        jPanel9.setLayout(null);

        jLabel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 51), 5));
        jPanel9.add(jLabel31);
        jLabel31.setBounds(680, 0, 400, 400);

        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel20.setBackground(new java.awt.Color(51, 51, 51));
        jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 51), 5));
        jPanel20.setEnabled(false);
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        error5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        error5.setForeground(new java.awt.Color(0, 255, 51));
        error5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 51, 255)));
        jPanel20.add(error5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 595, 50));

        jLabel105.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel105.setForeground(new java.awt.Color(51, 204, 0));
        jLabel105.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel105.setText("STREET VENDOR");
        jPanel20.add(jLabel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 13, 655, 50));

        jLabel106.setBackground(new java.awt.Color(0, 204, 51));
        jLabel106.setForeground(new java.awt.Color(51, 204, 0));
        jLabel106.setOpaque(true);
        jPanel20.add(jLabel106, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 655, 5));

        jLabel107.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel107.setForeground(new java.awt.Color(204, 51, 255));
        jLabel107.setText("NAME:");
        jPanel20.add(jLabel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 595, 50));

        jLabel108.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel108.setForeground(new java.awt.Color(204, 51, 255));
        jLabel108.setText("USER ID:");
        jPanel20.add(jLabel108, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 595, 50));

        jLabel109.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel109.setForeground(new java.awt.Color(0, 255, 51));
        jLabel109.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 51, 255)));
        jPanel20.add(jLabel109, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 595, 50));

        jLabel110.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel110.setForeground(new java.awt.Color(204, 51, 255));
        jLabel110.setText("ADHAR_CARD NO:");
        jPanel20.add(jLabel110, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 595, 50));

        jLabel111.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel111.setForeground(new java.awt.Color(204, 51, 255));
        jLabel111.setText("ADDRESS:");
        jPanel20.add(jLabel111, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 595, 50));

        jLabel112.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel112.setForeground(new java.awt.Color(204, 51, 255));
        jLabel112.setText("CONTACT:");
        jPanel20.add(jLabel112, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 595, 50));

        jLabel113.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel113.setForeground(new java.awt.Color(204, 51, 255));
        jLabel113.setText("DATE OF BIRTH:");
        jPanel20.add(jLabel113, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 595, 50));

        jLabel114.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel114.setForeground(new java.awt.Color(204, 51, 255));
        jLabel114.setText("GENDER:");
        jPanel20.add(jLabel114, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 700, 595, 50));

        jLabel115.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel115.setForeground(new java.awt.Color(204, 51, 255));
        jLabel115.setText("POSITION:");
        jPanel20.add(jLabel115, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 800, 595, 50));

        jLabel116.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel116.setForeground(new java.awt.Color(204, 51, 255));
        jLabel116.setText("JOINING DATE:");
        jPanel20.add(jLabel116, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 900, 595, 50));

        jLabel117.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel117.setForeground(new java.awt.Color(204, 51, 255));
        jLabel117.setText("EDUCATION:");
        jPanel20.add(jLabel117, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1000, 595, 50));

        jLabel118.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel118.setForeground(new java.awt.Color(204, 51, 255));
        jLabel118.setText("SALARY:");
        jPanel20.add(jLabel118, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1100, 595, 50));

        jLabel119.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel119.setForeground(new java.awt.Color(0, 255, 51));
        jLabel119.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 51, 255)));
        jPanel20.add(jLabel119, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 595, 50));

        jLabel120.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel120.setForeground(new java.awt.Color(0, 255, 51));
        jLabel120.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 51, 255)));
        jPanel20.add(jLabel120, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 595, 50));

        jLabel121.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel121.setForeground(new java.awt.Color(0, 255, 51));
        jLabel121.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 51, 255)));
        jPanel20.add(jLabel121, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 595, 50));

        jLabel122.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel122.setForeground(new java.awt.Color(0, 255, 51));
        jLabel122.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 51, 255)));
        jPanel20.add(jLabel122, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 650, 595, 50));

        jLabel123.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel123.setForeground(new java.awt.Color(0, 255, 51));
        jLabel123.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 51, 255)));
        jPanel20.add(jLabel123, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 750, 595, 50));

        jLabel124.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel124.setForeground(new java.awt.Color(0, 255, 51));
        jLabel124.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 51, 255)));
        jPanel20.add(jLabel124, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 850, 595, 50));

        jLabel125.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel125.setForeground(new java.awt.Color(0, 255, 51));
        jLabel125.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 51, 255)));
        jPanel20.add(jLabel125, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 950, 595, 50));

        jLabel126.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel126.setForeground(new java.awt.Color(0, 255, 51));
        jLabel126.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 51, 255)));
        jPanel20.add(jLabel126, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1050, 595, 50));

        jLabel127.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel127.setForeground(new java.awt.Color(0, 255, 51));
        jLabel127.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 51, 255)));
        jPanel20.add(jLabel127, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1150, 595, 50));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, 1247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );

        jScrollPane7.setViewportView(jPanel19);

        jPanel9.add(jScrollPane7);
        jScrollPane7.setBounds(0, 0, 680, 620);

        jButton7.setBackground(new java.awt.Color(255, 51, 51));
        jButton7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton7.setText("LEAVE");
        jButton7.setToolTipText("LEAVE");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton7);
        jButton7.setBounds(780, 530, 200, 50);

        jButton8.setBackground(new java.awt.Color(0, 204, 51));
        jButton8.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 51, 255));
        jButton8.setText("EDIT");
        jButton8.setToolTipText("EDIT");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton8);
        jButton8.setBounds(780, 430, 200, 50);

        jLayeredPane2.add(jPanel9, "card2");

        street_vendor.add(jLayeredPane2);
        jLayeredPane2.setBounds(560, 70, 1080, 615);

        jLayeredPane1.add(street_vendor, "card2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        add(jPanel3);
        jPanel3.setBounds(0, 80, 1730, 810);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 10, 0, new java.awt.Color(0, 204, 0)));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Employee");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 432, 80);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 432, 80);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Street Vendors");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 432, 80);

        add(jPanel2);
        jPanel2.setBounds(432, 0, 432, 80);

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Shop Vendors");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel3);
        jLabel3.setBounds(0, 0, 432, 80);

        add(jPanel4);
        jPanel4.setBounds(864, 0, 432, 80);

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Supplier");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel4);
        jLabel4.setBounds(0, 0, 432, 80);

        add(jPanel5);
        jPanel5.setBounds(1296, 0, 432, 80);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked

        PanelB();
        swithPanel(employee,jPanel1);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
PanelB();
        swithPanel(street_vendor,jPanel2);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
PanelB();
        swithPanel(ShopVendors,jPanel4);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
PanelB();
        swithPanel(Supplier,jPanel5);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        DefaultTableModel add1=new DefaultTableModel();
add1=(DefaultTableModel)jTable1.getModel();
TableRowSorter<DefaultTableModel> tr =new TableRowSorter<DefaultTableModel>(add1);
   jTable1.setRowSorter(tr);
   tr.setRowFilter(RowFilter.regexFilter(jTextField1.getText().trim()));



        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
edit_detail edit=new edit_detail();

  connection();
        try{
            pst=con.prepareStatement("SELECT * FROM `employee` where user_id='"+jLabel11.getText()+"';");
            rs=pst.executeQuery();
            while(rs.next()){
                
               edit.error1.setText(rs.getString("name"));
               edit.jLabel11.setText(rs.getString("user_id"));
                edit.jTextField1.setText(rs.getString("Address"));
             edit.jLabel6.setText(rs.getString("adhar_card_no"));
           edit.jTextField2.setText(rs.getString("Contact_no"));
             edit.jLabel23.setText(rs.getString("dob"));
                edit.jLabel24.setText(rs.getString("gender"));
               edit.jTextField3.setText(rs.getString("position"));
            edit.jLabel26.setText(rs.getString("join_date"));
         edit.jTextField4.setText(rs.getString("education"));
          edit.jTextField5.setText(rs.getString("salary"));
                BufferedImage im= ImageIO.read(rs.getBinaryStream("image"));
                resize1(edit.jLabel7,im);
            }
        }
        catch (Exception ex) {
            System.out.print(ex);
        }      
edit.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int st=jTable1.getSelectedRow();
        int a2=Integer.parseInt(jTable1.getValueAt(st, 0).toString());

        connection();
        try{
            pst=con.prepareStatement("SELECT * FROM `employee` where sr_no="+a2);
            rs=pst.executeQuery();
            while(rs.next()){
                System.out.print(rs.getInt("sr_no")+" "+rs.getBlob("image")+" "+rs.getString("name"));
                System.out.println();
                error1.setText(rs.getString("name"));
                jLabel11.setText(rs.getString("user_id"));
                jLabel5.setText(rs.getString("Address"));
                jLabel6.setText(rs.getString("adhar_card_no"));
                jLabel21.setText(rs.getString("Contact_no"));
                jLabel23.setText(rs.getString("dob"));
                jLabel24.setText(rs.getString("gender"));
                jLabel25.setText(rs.getString("position"));
                jLabel26.setText(rs.getString("join_date"));
                jLabel27.setText(rs.getString("education"));
                jLabel28.setText(rs.getString("salary"));
                BufferedImage im= ImageIO.read(rs.getBinaryStream("image"));
                resize1(jLabel7,im);

            }
        }
        catch (Exception ex) {
            System.out.print(ex);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
jt_refresh();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ShopVendors;
    private javax.swing.JPanel Supplier;
    private javax.swing.JPanel employee;
    private javax.swing.JLabel error1;
    private javax.swing.JLabel error5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel street_vendor;
    // End of variables declaration//GEN-END:variables
}
