/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forzon3;

import static forzon3.Dashboard1.jPanel5;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.opencv.core.Mat;
import org.opencv.core.MatOfByte;
import org.opencv.core.MatOfRect;
import org.opencv.core.Point;
import org.opencv.core.Rect;
import org.opencv.core.Scalar;
import org.opencv.imgcodecs.Imgcodecs;
import org.opencv.imgproc.Imgproc;
import org.opencv.objdetect.CascadeClassifier;
import org.opencv.videoio.VideoCapture;

/**
 *
 * @author chaitany
 */
public class street_vendor extends javax.swing.JPanel {
   public String eimg = "C:\\Users\\chaitany\\Desktop\\Forzon3\\src\\forzon3\\emimage\\job.jpg";

    /**
     * Creates new form street_vendor
     */
    public street_vendor() {
        initComponents();
    }
     public  ResultSet rs=null;
    public Connection  con=null;
    public PreparedStatement pst=null;
    public void connection(){
     try{
             con=DriverManager.getConnection("jdbc:mysql://localhost:3306/froze","root","");
    
        System.out.println("Database connection terminated");
     
      }
          catch(Exception e){
    System.out.println(e);    
        }
    

}


    public DaemonThread myThread = null;
    int count = 0;

    VideoCapture webSource = null;
    Mat frame = new Mat();
    MatOfByte mem = new MatOfByte();
    CascadeClassifier faceDetector = new CascadeClassifier(empoyeedas.class.getResource("haarcascade_frontalface_alt.xml").getPath().substring(1));
    MatOfRect faceDetections = new MatOfRect();
///    

    public void closecamera() {
        if (jButton1.getText().equals("Pause")) {

            myThread.runnable = false;            // stop thread
            // activate start button
            jButton1.setEnabled(true);     // deactivate stop button
           jButton1.setText("OPEN CAMERA");
            webSource.release();
        }
    }

    public class DaemonThread implements Runnable {

        protected volatile boolean runnable = false;

        @Override
        public void run() {
            synchronized (this) {
                while (runnable) {
                    if (webSource.grab()) {
                        try {
                            webSource.retrieve(frame);
                            Graphics g = jPanel8.getGraphics();
                            faceDetector.detectMultiScale(frame, faceDetections);
                            for (Rect rect : faceDetections.toArray()) {
                                // System.out.println("ttt");
                                Imgproc.rectangle(frame, new Point(rect.x, rect.y), new Point(rect.x + rect.width, rect.y + rect.height),
                                        new Scalar(0, 255, 0));
                            }
                            Imgcodecs.imencode(".bmp", frame, mem);
                            Image im = ImageIO.read(new ByteArrayInputStream(mem.toArray()));
                            BufferedImage buff = (BufferedImage) im;
                            if (g.drawImage(buff, 0, 0, 260, 260, 0, 0, buff.getWidth(), buff.getHeight(), null)) {
                                if (runnable == false) {
                                    System.out.println("Paused ..... ");
                                    this.wait();
                                }
                            }
                        } catch (Exception ex) {
                            System.out.println("Error!!");
                            ex.printStackTrace();
                        }
                    }
                }
            }
        }
    }
//End function camera

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel40 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setPreferredSize(new java.awt.Dimension(1690, 840));
        jPanel6.setLayout(null);

        jButton1.setBackground(new java.awt.Color(0, 255, 51));
        jButton1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton1.setText("OPEN CAMERA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1);
        jButton1.setBounds(1250, 90, 210, 40);

        jButton2.setBackground(new java.awt.Color(0, 255, 51));
        jButton2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton2.setText("SUBMIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2);
        jButton2.setBounds(1470, 90, 210, 40);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("STREET / SHOP VANDOR REGISTRATION FORM");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 0, 3, 0, new java.awt.Color(0, 255, 51)));
        jPanel6.add(jLabel6);
        jLabel6.setBounds(0, 20, 1750, 50);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 255, 51));
        jLabel7.setText("VENDOR NAME:");
        jPanel6.add(jLabel7);
        jLabel7.setBounds(40, 90, 950, 40);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 255, 51));
        jLabel9.setText("VENDOR ID:");
        jPanel6.add(jLabel9);
        jLabel9.setBounds(40, 190, 450, 40);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 255, 51));
        jLabel10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(204, 51, 255)));
        jPanel6.add(jLabel10);
        jLabel10.setBounds(40, 240, 450, 40);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 255, 51));
        jLabel11.setText("ADHAR_CARD NO.:");
        jPanel6.add(jLabel11);
        jLabel11.setBounds(40, 290, 450, 40);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 255, 51));
        jLabel13.setText("ADDRESS:");
        jPanel6.add(jLabel13);
        jLabel13.setBounds(40, 390, 950, 40);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 255, 51));
        jLabel15.setText("CONTACT NO.:");
        jPanel6.add(jLabel15);
        jLabel15.setBounds(40, 490, 450, 40);

        jLabel17.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 255, 51));
        jLabel17.setText("DATE OF BIRTH:");
        jPanel6.add(jLabel17);
        jLabel17.setBounds(40, 590, 450, 40);

        jLabel19.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 255, 51));
        jLabel19.setText("EDUCATION:");
        jPanel6.add(jLabel19);
        jLabel19.setBounds(40, 690, 950, 40);

        jLabel21.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 255, 51));
        jLabel21.setText("TYPE OF VENDOR?");
        jPanel6.add(jLabel21);
        jLabel21.setBounds(540, 190, 450, 40);

        jLabel36.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 255, 51));
        jLabel36.setText("JOINING DATE:");
        jPanel6.add(jLabel36);
        jLabel36.setBounds(540, 290, 450, 40);

        jLabel38.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 255, 51));
        jLabel38.setText("GENDER:");
        jPanel6.add(jLabel38);
        jLabel38.setBounds(540, 490, 450, 40);

        jLabel48.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(0, 255, 51));
        jLabel48.setText("VENDOR PHOTO:");
        jPanel6.add(jLabel48);
        jLabel48.setBounds(1040, 90, 650, 40);

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 51, 255), 3));
        jPanel6.add(jPanel8);
        jPanel8.setBounds(1040, 140, 650, 650);

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(204, 51, 255)));
        jPanel6.add(jTextField1);
        jTextField1.setBounds(40, 140, 950, 40);

        jRadioButton1.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButton1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("STREET VENDOR");
        jPanel6.add(jRadioButton1);
        jRadioButton1.setBounds(540, 240, 230, 40);

        jRadioButton2.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButton2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("SHOP VENDOR");
        jPanel6.add(jRadioButton2);
        jRadioButton2.setBounds(770, 240, 220, 40);

        jTextField2.setBackground(new java.awt.Color(0, 0, 0));
        jTextField2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(204, 51, 255)));
        jPanel6.add(jTextField2);
        jTextField2.setBounds(40, 340, 450, 40);

        jTextField3.setBackground(new java.awt.Color(0, 0, 0));
        jTextField3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(204, 51, 255)));
        jPanel6.add(jTextField3);
        jTextField3.setBounds(40, 440, 950, 40);

        jTextField4.setBackground(new java.awt.Color(0, 0, 0));
        jTextField4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(204, 51, 255)));
        jPanel6.add(jTextField4);
        jTextField4.setBounds(40, 540, 450, 40);

        jTextField5.setBackground(new java.awt.Color(0, 0, 0));
        jTextField5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(204, 51, 255)));
        jPanel6.add(jTextField5);
        jTextField5.setBounds(40, 740, 950, 40);

        jRadioButton3.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButton3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("MALE");
        jRadioButton3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(204, 51, 255)));
        jPanel6.add(jRadioButton3);
        jRadioButton3.setBounds(540, 540, 220, 40);

        jRadioButton4.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButton4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("FEMALE");
        jRadioButton4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(204, 51, 255)));
        jPanel6.add(jRadioButton4);
        jRadioButton4.setBounds(770, 540, 220, 40);

        jDateChooser1.setBackground(new java.awt.Color(0, 0, 0));
        jDateChooser1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 51, 255), 3));
        jDateChooser1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.add(jDateChooser1);
        jDateChooser1.setBounds(540, 340, 450, 40);

        jDateChooser2.setBackground(new java.awt.Color(0, 0, 0));
        jDateChooser2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 51, 255), 3));
        jDateChooser2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.add(jDateChooser2);
        jDateChooser2.setBounds(40, 640, 450, 40);

        jLabel40.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 255, 51));
        jLabel40.setText("SHOP NAME:");
        jPanel6.add(jLabel40);
        jLabel40.setBounds(540, 590, 450, 40);

        jTextField6.setBackground(new java.awt.Color(0, 0, 0));
        jTextField6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(204, 51, 255)));
        jPanel6.add(jTextField6);
        jTextField6.setBounds(540, 640, 450, 40);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel1);
        jPanel1.setBounds(1050, 140, 630, 640);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1715, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 901, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (evt.getActionCommand() == "OPEN CAMERA") {
            jButton1.setText("Pause");
            webSource = new VideoCapture(0); // video capture from default cam
            myThread = new street_vendor.DaemonThread(); //create object of threat class
            Thread t = new Thread(myThread);
            t.setDaemon(true);
            myThread.runnable = true;
            t.start();          //start thrad

        }
        if (evt.getActionCommand() == "Pause") {
            // deactivate start button
            closecamera();
            eimg = "C:\\Users\\chaitany\\Desktop\\Forzon3\\src\\forzon3\\emimage\\" + jLabel10.getText() + ".jpg";
            Imgcodecs.imwrite(eimg, frame);


        }

   
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   
        
            File fimg = new File(eimg); 
             if (fimg .exists()) 
             
             {try{
                   
                connection();
                pst=con.prepareStatement("insert into  vendor_information(`vendor_Id`, `vendor_name`, `type`, `adhcard`, `ADDRESS`, `joindate_date`, `contact_no`, `gender`, `dob`, `education`, `SHOP_NAME`, `Image`) values(?,?,?,?,?,?,?,?,?,?,?,?)");
            pst.setString(1,jLabel10.getText());
            pst.setString(2,jTextField1.getText());
            String types="STREET VENDOR";
            if(jRadioButton2.isSelected()){
              types="SHOP VENDOR";  
            }
            pst.setString(3,types);
            pst.setString(4, jTextField2.getText());
              pst.setString(5, jTextField3.getText());
              java.util.Date date=new java.util.Date();
			date=jDateChooser1.getDate();
			java.sql.Date sqlDate=new java.sql.Date(date.getTime());

                pst.setDate(6, sqlDate);
                pst.setInt(7,Integer.parseInt(jTextField4.getText()));
             String gender="Male";
            if(jRadioButton2.isSelected()){
             gender="Female";  
            }
            pst.setString(8,gender);
                java.util.Date date1=new java.util.Date();
			date1=jDateChooser2.getDate();
			java.sql.Date sqlDate1=new java.sql.Date(date1.getTime());

                pst.setDate(9, sqlDate1);
                pst.setString(10, jTextField5.getText());
                pst.setString(11, jTextField6.getText());
            InputStream in = new FileInputStream(fimg);

              pst.setBlob(7, in);
            pst.executeUpdate();
                JOptionPane.showMessageDialog(this,"Succesfully Sign up"); 
   
                }
                catch(Exception e){
                    System.out.println(e);
                }
             }
                         else
             {
                   jPanel5.setVisible(false);
                      JOptionPane.showMessageDialog(null,"please insert picture"); 
   
             }
             
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    public static javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    public static javax.swing.JLabel jPanel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
